### ISSUE TITLE
doInBackground error

### ISSUE THREAD

**Issue by logo17** [AltBeacon/android-beacon-library#56] opened 2014-11-18 20:56 UTC
I have had this error many times. It happens with the app running and the screen locked about several minutes. Then when I unlocked the screen and tried to use the app I got this error.

java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:299)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
            at java.util.concurrent.FutureTask.run(FutureTask.java:239)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.util.ConcurrentModificationException
            at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
            at org.altbeacon.beacon.service.BeaconService$ScanProcessor.doInBackground(BeaconService.java:639)
            at org.altbeacon.beacon.service.BeaconService$ScanProcessor.doInBackground(BeaconService.java:632)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)

**Comment by gelldur** [comment] 2015-07-22 07:23
@mturki here is fix for it: https://github.com/AltBeacon/android-beacon-library/pull/245

**Comment by ryot** [comment] 2017-02-09 19:30
This crash has been reoccurring in 2.9.2, see the recently added comments on PR #245

**Comment by TonyTangAndroid** [comment] 2017-09-07 02:45
I have run into this crash on 2.12.2. Here is the stack trace

> java.lang.RuntimeException: An error occurred while executing doInBackground()
                                         at android.os.AsyncTask$3.done(AsyncTask.java:353)
                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                         at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                         at java.lang.Thread.run(Thread.java:764)
                                      Caused by: java.util.ConcurrentModificationException
                                         at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
                                         at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
                                         at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator.findCalculatorForModel(ModelSpecificDistanceCalculator.java:123)
                                         at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator.findCalculatorForModelWithLock(ModelSpecificDistanceCalculator.java:105)
                                         at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator$1.onComplete(ModelSpecificDistanceCalculator.java:251)
                                         at org.altbeacon.beacon.distance.ModelSpecificDistanceUpdater.doInBackground(ModelSpecificDistanceUpdater.java:30)
                                         at org.altbeacon.beacon.distance.ModelSpecificDistanceUpdater.doInBackground(ModelSpecificDistanceUpdater.java:16)
                                         at android.os.AsyncTask$2.call(AsyncTask.java:333)

**Comment by davidgyoung** [comment] 2017-09-07 20:06
@TonyTangAndroid, do you know the OS version on which you have seen this crash?

**Comment by TonyTangAndroid** [comment] 2017-09-08 02:28
**Android 8.0 Google Pixel.** 
Sorry that I was too quick to paste the stack trace and forgot to provide this critical information.

**Comment by davidgyoung** [comment] 2017-09-08 20:52
Fixed in #584

**Closed by davidgyoung** 2017-09-08 20:52 UTC
