### ISSUE TITLE
NPE after calling mRegionBootstrap.disable() method

### ISSUE THREAD

**Issue by bharatjyoti** [AltBeacon/android-beacon-library#916] opened 2019-08-19 19:11 UTC
Hi, got null pointer exception after calling mRegionBootstrap.disable() method.
Stack trace-

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.altbeacon.beacon.service.MonitoringStatus org.altbeacon.beacon.service.ScanState.getMonitoringStatus()' on a null object reference
        at org.altbeacon.beacon.service.ScanJob.startPassiveScanIfNeeded(ScanJob.java:139)
        at org.altbeacon.beacon.service.ScanJob.onStopJob(ScanJob.java:171)
        at android.app.job.JobService$1.onStopJob(JobService.java:67)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:117)
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7076) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by davidgyoung** [comment] 2019-08-19 22:19
Duplicate of #887

**Closed by davidgyoung** 2019-08-19 22:19 UTC
