### ISSUE TITLE
didExitRegion() followed immediately by didEnterRegion() for the same region

### ISSUE THREAD

**Issue by matiash** [AltBeacon/android-beacon-library#27] opened 2014-08-28 23:04 UTC
I'm using almost the latest sources (from Aug 27th) and I'm experiencing this problem, testing with a single beacon. With everything stationary and a while ranging a single monitored region, every couple of minutes I get exit/enter events for it.

Is this a known issue with the library? How can/should I investigate this problem?

**Comment by davidgyoung** [comment] 2015-01-03 20:16
Closing issue as the configured advertising frequency appears to be the root cause.

**Closed by davidgyoung** 2015-01-03 20:16 UTC

**Comment by hearbeathorror** [comment] 2015-03-12 05:35
@naderz - do mind sharing on how you got this fixed? please,

**Comment by bhutta123** [comment] 2016-03-24 10:54
@davidgyoung As you mentioned in one of your comment that if library doesn't detect beacon for 10 seconds didExitRegion() gets called. How can i configure this value? I wan't to change this value to 1 minute to avoid to frequent enter/exit calls.

**Comment by davidgyoung** [comment] 2016-03-24 11:28
This setting is now configurable.  You can change the default 10 secs to 60 secs with:

`beaconManager.setRegionExitPeriod(60000l)`

That said, this is still not the recommended solution to the problem described in this issue.  Increasing the frequency of beacon transmissions will give better results.

**Comment by bhutta123** [comment] 2016-03-24 12:18
Thanks for the quick reply. Increasing frequency decrease battery life a lot. I have tested with 100ms frequeny also if device is far from the beacon (aprox boundry) it keeps entering and exiting the region within minutes though device is static.

**Comment by andersborgabiro** [comment] 2016-03-24 12:30
My experience is that a beacon at 0 dBm and 1 second ping lasts 1 year on a CR2477 battery (mileage may vary), so 100 ms would be very draining. A lower power doesn't give good enough proximity precision, nor reach. I therefore recommend USB beacons, if there's a way to connect them.
