### ISSUE TITLE
don't receive didEnterRegion callback when screen is off

### ISSUE THREAD

**Issue by TracyEminem** [AltBeacon/android-beacon-library#789] opened 2018-11-30 09:17 UTC
### Expected behavior

keep receiving didEnterRegion callback when screen is off

### Actual behavior

when the phone is charging nomatter it is locked or not i can receive didEnterRegion callback immediately,but when the phone is locked and not charging i can't receive didEnterRegion callback anymore.

Is this library uses something like google play service or something that can't be used in china?

### Steps to reproduce this behavior

when the phone is locked and not charging

### Mobile device model and OS version

huawei honor v8 ,android 8.0

### Android Beacon Library version

android-beacon-library-2.15.3-beta1

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment] 2018-11-30 12:17
This sounds like a duplicate of #554.  Please comment there if you have more I fo to add.

Unfortunately, we have yet to find a viable workaround for Huawei's proprietary Android extensions blocking scans with the screen off.

**Closed by davidgyoung** 2018-11-30 12:17 UTC
