### ISSUE TITLE
How can I trigger the startRangingBeaconsInRegion when ever didenter triggers in plugin code??

### ISSUE THREAD

**Issue by saty932** [AltBeacon/android-beacon-library#712] opened 2018-07-20 05:57 UTC
Thanks for wonderful plugin.
What we need is we are monitoring the beacons using uuid so when ever we enters into region it's able to trigger did enter region.It's able to sending the uuid details based on that we need to scan beacons and find out all beacons in that  region after finding out which beacon is near we need to trigger one notification.

I already modified that plugin it's working fine.Only thing is I am getting some error regarding cordova context error.

`
 private void createMonitorCallbacks(final CallbackContext callbackContext) {
        //Monitor callbacks
      iBeaconManager.setMonitorNotifier(new MonitorNotifier() {
        @Override
        public void didEnterRegion(Region region) {

            try {

                JSONObject monitorData = new JSONObject();
                monitorData.put("identifier", "1");
                monitorData.put("uuid","4b54504c-5546-4f00-0000-000000000001");
                monitorData.put("typeName", "BeaconRegion");
                monitorData.put("NotifyEntryStateOnDisplay", new Boolean(true));
                startRangingBeaconsInRegion(monitorData,callbackContext);
            }
            catch (Exception e){

            }
          
          showNotification();
          //    Log.i(TAG, "Show your notification here");
          debugLog("didEnterRegion INSIDE for " + region.getUniqueId());
          dispatchMonitorState("didEnterRegion", MonitorNotifier.INSIDE, region, callbackContext);
        }
`
in above code with in did enter region I am calling startrangingregion it's working fine but I am getting small error.

Error in console
`
LocationManager.js:124 Delegate registration promise is already been resolved, all subsequent callbacks should provide an "eventType" field.
`
can any one help me with this?Is there any better way do it???

**Comment by davidgyoung** [comment] 2018-07-20 11:57
You probably want to post this issue in the repo of the Cordova plugin project you are modifying.  This is the repo for the native Java library the plugin uses, so the problem is a bit out of scope here and folks here are unlikely to have the Cordova plugin  expertise needed to solve this problem.

**Closed by davidgyoung** 2018-07-20 11:57 UTC
