### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by soumithganji** [AltBeacon/android-beacon-library#1002] opened 2020-09-10 16:32 UTC
![image](https://user-images.githubusercontent.com/57139894/92763498-3e683880-f3b1-11ea-9627-5e552ae76fd7.png)

**Comment by davidgyoung** [comment] 2020-09-10 17:03
This is  a duplicate of the issue below.  Please look at the documented solution and if you need help implementing it with your project, please open a question on StackOverflow.com

https://github.com/AltBeacon/android-beacon-library/issues/919#issuecomment-607440770

**Closed by davidgyoung** 2020-09-10 17:03 UTC
