### ISSUE TITLE
Not seeing beacons after App is killed - ACTION_POWER_CONNECTED 

### ISSUE THREAD

**Issue by cokeby190** [AltBeacon/android-beacon-library#44] opened 2014-10-21 06:56 UTC
Hi,

I have read this on StackOverflow :
1. The app has been installed but never launched
2. The app has been launched once but since rebooted
3. The app has been killed from the task switcher
   Using the code above, here is the expected behavior in each case:

The app will not be running and cannot auto-launch the Activity.
The app will start scanning for beacons periodically after boot and will launch the Activity when one is detected.
The app will not be running and cannot auto-launch until charger connect/disconnect or reboot. After that time, behavior is as in (2). More details on this case are available here.

And my current behavior is in case (3), and when the app is killed, and the charger is disconnected and reconnected, it doesnt start the app again, nor does it re-detect the beacons. 

I looked through the logcat, 

10-21 15:00:21.013 W/ActivityManager(  951): Scheduling restart of crashed service <app-package-name>/org.altbeacon.beacon.service.BeaconService in 1000ms
10-21 15:00:22.133 I/BeaconService(11088): beaconService version 2.0-beta3 is starting up'

And the logcat stopped showing any more logs from BeaconService.

**Comment by davidgyoung** [comment] 2015-01-21 22:52
I have created an app to test devices to make sure they can receive the ACTION_POWER_CONNECTED event in order to restart beacon detections.  Please try running this app (instructions in the README.md, binary download available under releases) and report the results along with your model number here.

https://github.com/davidgyoung/power-connect-tester

**Comment by davidgyoung** [comment] 2015-01-21 23:09
@cokeby190, @jessolo, @f4t-t0ny, I'd appreciate it if you could run the test above on your devices to help get to the bottom of this issue.

**Comment by markvandertol** [comment] 2015-01-22 11:12
I've tried the app on my Nexus 5 (Android 4.4) and there it works as expected when you kill the app through the app switcher. However if you force-stop the app through the app settings, then Android won't automatically restart the app until the app is launched manually by the user again. This is by design.

Maybe some launchers perform a "force stop" instead of a "normal stop" when closing a task through the task switcher? I don't know if there is a easy way to see if an app has been "force stopped".

I don't see a clear distinction for a force stop and the other ways the app gets killed in http://altbeacon.github.io/android-beacon-library/resume-after-terminate.html Maybe something that could be added.

**Comment by davidgyoung** [comment] 2015-01-29 01:50
@markvandertol  I think you have a good point.    Per the docs [here](http://developer.android.com/about/versions/android-3.1.html) if an app is force stopped its app package is put in a stopped state (same as if app is never run) and it cannot receive any broadcast intents until the app is explicitly launched again.  

Now, reading back on the folks who reported the problem in this issue, it is not exactly clear *how* they killed the app.   Did they (a) swipe the app off of the recent apps list?  or (b) hit the "FORCE STOP" button on the App info screen under settings.

@cokeby190 and @f4t-t0ny, can you please clarify?

I doubt that some phone builds perform a "force stop" when closing an app through the task switcher, but it is possible.  One way to verify this is to close the app through the task switcher, then go to the app info page in settings and see if the "force stop" button is greyed out.  If it is, then a force stop was performed.

@markvandertol, I agree that clarification should be made in http://altbeacon.github.io/android-beacon-library/resume-after-terminate.html.  But I'd like to fully understand what we should clarify first. :)

**Comment by davidgyoung** [comment] 2015-01-29 02:52
I have verified that on a Nexus 5 / Android 5 both of the following intents are received after killing the task from the task switcher, and neither are received after doing a force stop.  When the intents are received, they have the flags below:

```
android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (FLAG_ACTIVITY_CLEAR_TOP | FLAG_EXCLUDE_STOPPED_PACKAGES)
android.intent.action.BOOT_COMPLETED flg=0x8000010 (FLAG_RECEIVER_NO_ABORT | FLAG_EXCLUDE_STOPPED_PACKAGES)
```

This confirms that these intents are not supposed to be delivered to stopped packages.  (Those killed through force stop).

**Comment by chrisriesgo** [comment] 2015-02-16 02:10
Using the power-connect-test, I've confirmed that the app works as expected on:

__Model number:__ SAMSUNG-SGH-I337 (Galaxy S4) 
__Android version:__ 4.4.4 
__Build Number:__ KTU84P.I337UCUFNJ4

**Comment by kapilkumarchawala** [comment] 2015-03-10 10:37
I downloaded the reference application and it worked fine in background and foreground but not working after killing the app from task switcher. I tested using nexus 5. Same is happening with my app in which I have used this plugin.

Process that I followed is:
Launched the app from eclipse-> detached the device from computer->Killed the app -> attached the device to the computer-> transmitted the registered beacon.
but it is not detecting that beacon. I have issued a local notification from the didenter method which appears when app is running in foreground or background but not  appears when app is killed.

**Comment by davidgyoung** [comment] 2015-03-11 22:10
@kapilkumarchawala, Your results do not match those of mine on the Nexus 5.  Can you please confirm your Nexus 5 version and try with the following app: https://github.com/davidgyoung/power-connect-tester  (See instructions in the README.md)

**Comment by kapilkumarchawala** [comment] 2015-03-13 06:34
Nexus 5 OS version is 5.1

**Comment by davidgyoung** [comment] 2015-03-13 13:22
It is possible this has changed in Android 5.1.  My tests so far have only been on 5.0 on the Nexus 5, I will retest when I get the OS upgrade.

**Comment by jnivard** [comment] 2015-09-01 12:54
Hai

I did set up the project in eclips. But when I start the project I recieve a message : Unable to create the application BeaconServiceNotDelclared exception. The BeaconService is not properly declared

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="org.altbeacon.beaconreference"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="17"
        android:targetSdkVersion="21" />
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>

    <application 
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" 
        android:name="BeaconReferenceApplication">
        <activity
            android:name="org.altbeacon.beaconreference.MonitoringActivity"
            android:label="@string/app_name" >
            <intent-filter>
				<action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="org.altbeacon.beaconreference.RangingActivity"
            android:label="@string/app_name" >
            <intent-filter>
            </intent-filter>
        </activity>
        
    </application>

 Project target.
target=android-21
manifestmerger.enabled=true
android.library.reference.1=../android-beacon-library-eclipse

**Comment by davidgyoung** [comment] 2015-09-01 14:41
@jnivard, for assistance using this library, please create a question on Stackoverflow.com.  this forum is reserved for feature requests and reporting reproducible bugs with the library itself.

To save you time, I will say right off that it appears manifest merging is not working in your Eclipse setup.  If you can't fix this, you might try copying entries manually from here: https://github.com/AltBeacon/android-beacon-library/blob/master/src/main/AndroidManifest.xml  

If you need more help, please open a question on StackOverflow.com

**Comment by davidgyoung** [comment] 2015-09-21 18:10
Model Number: Nexus 9
Build Number: MPA44l (Android 6.0 Preview)

The app works as expected.  Power connect and disconnect events are passed to the app, even after you kill the app with the task switcher.

**Comment by AlexTrotsenko** [comment] 2015-11-10 10:52
Hi @davidgyoung ,

I have just read http://altbeacon.github.io/android-beacon-library/resume-after-terminate.html.

Please, correct me if I am wrong, but following statement misses Negation ("NOT" word)
>Terminating an app as described in case 5 above will typically allow them to resume automatically without starting them manually -- this is a limitation imposed by the operating system. 

I know, that It's not very linked to the current issue, but I don't know any better place to report this kind of issues.

**Comment by davidgyoung** [comment] 2015-11-10 13:21
Good catch, Alex.  I have fixed this and added the missing "not"

**Comment by tyler77** [comment] 2016-02-17 16:38
Hi @davidgyoung, maybe my P8 Huawey have the same issue. It seems that after killing the App from the task switcher, the App does't detect the beacons anymore. But I have some trouble if i import  

https://github.com/davidgyoung/power-connect-tester

in Eclipse. Is the App still working? Could you please explain me how to import it correctly into Eclipse?

I would like to have a confirmation that also P8 blocks the reboot.

**Comment by davidgyoung** [comment] 2016-02-18 02:37
@tyler77, the project only builds with Android Studio, but you can download a binary release here: https://github.com/davidgyoung/power-connect-tester/releases

Please let us know what you find on the P8

**Comment by davidgyoung** [comment] 2018-03-06 03:47
closing due to inactivity

**Closed by davidgyoung** 2018-03-06 03:47 UTC
