### ISSUE TITLE
BluetoothCrashResolver not resolving bluetooth crash

### ISSUE THREAD

**Issue by stefansgit** [AltBeacon/android-beacon-library#274] opened 2015-08-31 10:23 UTC
Tested on Samsung S3 with Android 4.3. I have gimbal beacons that have already filled up the bluetooth stack making the bluetooth crash repeatedly. When testing with your library Bluetooth keep crashing. I expected the class to clear the bluetooth stack if it detected a bluetooth crash. Or does it just prevent it from happening if the bluetooth stack is not yet full?

**Comment by davidgyoung** [comment] 2015-08-31 13:34
This is a duplicate of the issue currently being tracked here:  https://github.com/RadiusNetworks/bluetooth-crash-resolver/issues/6

I am in search of a  volunteer with a rooted Samsung Galaxy S3 who can do some tests to make the crash resolver compatible.  If you would like to volunteer please comment on that issue.

**Closed by davidgyoung** 2015-08-31 13:34 UTC
