### ISSUE TITLE
Background scanning on Android/After app is killed

### ISSUE THREAD

**Issue by giladrom** [AltBeacon/android-beacon-library#721] opened 2018-08-12 21:08 UTC
### Expected behavior
Altbeacon should wake up the main process and find beacons

### Actual behavior
Altbeacon does not find any beacons during interval scan after main process is killed using Clear All from the task switcher. 

### Steps to reproduce this behavior
1. Run app, make sure beacons are detected
2. Terminate app

### Mobile device model and OS version
Over 50 Android devices from various manufacturers ranging from Android 6 to 9.

### Android Beacon Library version
2.14/2.15

I'm using the cordova ibeacon library which is a wrapper over Altbeacon, so trying to find where the problem is.

Here is the Logcat output from the scheduled jobs - If there's anything missing, please let me know:

```
08-12 13:59:50.294 13769-13769/com.gethuan.huanapp I/ScanJob: Scan job runtime expired: org.altbeacon.beacon.service.ScanJob@93024b1
08-12 13:59:50.303 13769-13800/com.gethuan.huanapp D/BluetoothAdapter: isLeEnabled(): ON
08-12 13:59:50.320 13769-13800/com.gethuan.huanapp D/BluetoothAdapter: isLeEnabled(): ON
08-12 13:59:50.321 13769-13800/com.gethuan.huanapp D/BluetoothLeScanner: could not find callback wrapper
08-12 13:59:50.454 1588-4493/? D/PMS: releaseWL(9a5016e): PARTIAL_WAKE_LOCK  *job*/com.gethuan.huanapp/org.altbeacon.beacon.service.ScanJob 0x1 WorkSource{10123} 0x0
08-12 13:59:50.582 13769-13769/com.gethuan.huanapp I/ScanJob: Using immediateScanJobId from manifest: 208352939
08-12 13:59:50.588 13769-13769/com.gethuan.huanapp I/ScanJob: Using periodicScanJobId from manifest: 208352940
08-12 13:59:50.588 13769-13769/com.gethuan.huanapp W/JobInfo: Specified interval for 208352940 is +5m0s0ms. Clamped to +15m0s0ms
08-12 13:59:50.589 13769-13769/com.gethuan.huanapp W/JobInfo: Specified flex for 208352940 is 0. Clamped to +5m0s0ms
    Specified interval for 208352940 is +5m0s0ms. Clamped to +15m0s0ms
    Specified flex for 208352940 is 0. Clamped to +5m0s0ms
08-12 13:59:50.635 1588-1917/? D/AlarmManager: sending alarm to uid=1000, package=android, listener=android.app.AlarmManager$ListenerWrapper@173afd9, listenerTag=WifiConnectivityManager Schedule Periodic Scan Timer, t=2, cnt=1, w=969097, Int=0, ws=null
    sending alarm to uid=1000, package=android, listener=android.app.AlarmManager$ListenerWrapper@8ac2d9e, listenerTag=*job.delay*, t=2, cnt=1, w=1050056, Int=0, ws=WorkSource{10123 com.gethuan.huanapp}
08-12 13:59:50.638 1588-1917/? D/AlarmManager: sending alarm to uid=1000, package=android, listener=android.app.AlarmManager$ListenerWrapper@fe7d84c, listenerTag=*job.deadline*, t=2, cnt=1, w=1050056, Int=0, ws=WorkSource{10123 com.gethuan.huanapp}
08-12 13:59:50.650 1588-1588/? D/PMS: acquireWL(2e02d38): PARTIAL_WAKE_LOCK  *job*/com.gethuan.huanapp/org.altbeacon.beacon.service.ScanJob 0x1 1588 1000 WorkSource{10123}
08-12 13:59:50.756 13769-13769/com.gethuan.huanapp I/CycledLeScanner: Using Android O scanner
08-12 13:59:50.759 13769-13769/com.gethuan.huanapp I/ScanJob: Using immediateScanJobId from manifest: 208352939
    Running immediate scan job: instance is org.altbeacon.beacon.service.ScanJob@55aba5e
08-12 13:59:50.760 13769-13769/com.gethuan.huanapp I/ScanJob: scanJob version 2.15 is starting up on the main process
08-12 13:59:50.767 13769-13769/com.gethuan.huanapp W/ModelSpecificDistanceCalculator: Cannot find match for this device.  Using default
    Cannot find match for this device.  Using default
08-12 13:59:50.772 13769-13769/com.gethuan.huanapp D/BluetoothAdapter: isLeEnabled(): ON
08-12 13:59:50.780 13769-13769/com.gethuan.huanapp I/ScanJob: Scan job running for 300000 millis
08-12 13:59:50.781 13769-13941/com.gethuan.huanapp D/BluetoothAdapter: isLeEnabled(): ON
08-12 13:59:50.786 13769-13781/com.gethuan.huanapp D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=6 mScannerId=0
08-12 13:59:57.442 13769-13941/com.gethuan.huanapp D/BluetoothAdapter: isLeEnabled(): ON
08-12 13:59:57.447 13769-13941/com.gethuan.huanapp D/BluetoothAdapter: isLeEnabled(): ON
08-12 13:59:57.452 13769-13781/com.gethuan.huanapp D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=6 mScannerId=0
08-12 14:00:04.129 13769-13941/com.gethuan.huanapp D/BluetoothAdapter: isLeEnabled(): ON
08-12 14:00:04.143 13769-13941/com.gethuan.huanapp D/BluetoothAdapter: isLeEnabled(): ON
08-12 14:00:04.153 13769-13781/com.gethuan.huanapp D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=6 mScannerId=0

```

**Comment by davidgyoung** [comment] 2018-08-12 21:58
Apologies, @giladrom since your test case is in a Cordova setup, it is really out of scope of this project.  This project is focussed on providing native beacon detection functionality. 

While I'm totally in support of Cordova wrapper libraries like the [Codova iBeacon Plugin](https://github.com/petermetz/cordova-plugin-ibeacon) and the related [background notification plugin](https://github.com/saty932/cordova-plugin-beacon-monitoring-in-background-with-notifications-android), I just don't have the expertise to troubleshoot this librarys use from within Cordova.  If you are using one of those plugins, opening an issue on one of those other repos may be more appropriate.

I do know that getting Cordova callbacks after an app is killed is a challenge because something must bootstrap the Webview that hosts the Cordova runtime.  I don't know if that is the specific issue here, or if it is an issue at a lower level.  Again, since this isn't a Cordova project, I just don't have the expertise to say.   There was some discussion about a solution to this problem in [this issue in the Cordova iBeacon Plugin project.](https://github.com/petermetz/cordova-plugin-ibeacon/issues/141)

If the issue you are experiencing can be reproduced natively using the native [reference app](https://github.com/AltBeacon/android-beacon-library-reference) for this library, then we may be able to help here  In that case, please do create an issue with instructions to reproduce using the native reference app.

**Closed by davidgyoung** 2018-08-12 21:58 UTC
