### ISSUE TITLE
Android 13 Crash

### ISSUE THREAD

**Issue by DarrenMiddleton** [AltBeacon/android-beacon-library#1083] opened 2022-04-19 17:48 UTC
When I start ranging for Bluetooth devices using the altbeacon library I get the following crash.

`    java.lang.RuntimeException: Unable to create service org.altbeacon.beacon.service.BeaconService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4524)
        at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7850)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference`

It happens on all Android devices I have tested that are running [Android 13.](https://developer.android.com/about/versions/13) The altbeacon library version is 2.19.

**Comment by joeywittig** [comment] 2022-05-10 08:02
Same is happening for me.

**Comment by davidgyoung** [comment] 2022-06-01 22:11
After reviewing the documents changes in Android 13, I see nothing announced that might cause the problem.   This appears to be a bug in Android 13.

In ActivityThread.java:4524 (inside handleCreateService) there is a call to  xxxxx.toString() when xxxx is null, thereby causing a crash.   Unfortunately Android 13 source is not available.  If I look at the latest version of that ActivityThread.java the lines don't match up:

https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/ActivityThread.java#4516

However, I do see a number of string concatenations that would cause a toString() call like this: `Slog.v(TAG, "Creating service " + data.info.name);`

Could data.info.name be unexpectedly null?

This should come from the android:name element of the XML declaration of the BeaconService, which is declared in the library AndroidManifest.xml file as:

```
        <service android:enabled="true"
            android:exported="false"
            android:isolatedProcess="false"
            android:label="beacon"
            android:name=".service.BeaconService"
            />
```

But maybe something in Android 13 causes this to become null later on?

You might try two things:

1. Check your merged manifest after a build and see if this service declaration has a proper name like `android:name="org.altbeacon.beacon.service.BeaconService"`.  You should find that in `build/intermediates/merged_manifests/debug/AndroidManifest.xml`.  If it does not have  a name declaration this could be the problem, and the next option might help.

2. You could try making your own service entry in your app's AndroidManifest.xml to override this declaration and force the service to have a name.  You could do something like this:

```
    <service android:name="org.altbeacon.beacon.service.BeaconService"
                    android:exported="false"
                    android:isolatedProcess="false"
                    android:label="beacon"
                    android:name="org.altbeacon.beacon.service.BeaconService"
                     tools:node="replace">
    </service>
```

**Comment by FabFabulous** [comment] 2022-06-16 10:45
I have the same issue. I checked the merged manifest and I do have `android:name="org.altbeacon.beacon.service.BeaconService"`.

**Comment by DarrenMiddleton** [comment] 2022-06-16 21:17
I think this should work.

        <service android:enabled="true"
            android:exported="false"
            android:isolatedProcess="true"
            android:label="beacon"
            android:name=".service.BeaconService"
            />

**Comment by davidgyoung** [comment] 2022-06-16 21:33
@FabienWitick can you please share your full merged manifest <service> declaration in case that gives any clues?  

@DarrenMiddleton , did you try the suggestion you posted?  I wouldn't think the `android:isolatedProcess="true"` would be helpful -- I would think that would break the library's ability to send scan results via the library APIs.

**Comment by FabienWitick** [comment] 2022-06-17 17:52
Here is my full merged manifest :
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.myzee.witick.debug"
    android:versionCode="73"
    android:versionName="3.3.1" >

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="30" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission
        android:name="android.permission.BLUETOOTH"
        android:required="false" />
    <uses-permission
        android:name="android.permission.BLUETOOTH_ADMIN"
        android:required="false" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <uses-permission-sdk-23 android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission-sdk-23 android:name="android.permission.VIBRATE" />

    
    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.front"
        android:required="false" /> 
    
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.flash"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.screen.landscape"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.wifi"
        android:required="false" />

    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.WAKE_LOCK" /> 
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="true" />

    <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

    <application
        android:name="com.myzee.witick.AppSingleton"
        android:allowBackup="false"
        android:appComponentFactory="androidx.core.app.CoreComponentFactory"
        android:debuggable="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme" >
        <meta-data
            android:name="com.mixpanel.android.MPConfig.EventsEndpoint"
            android:value="https://api-eu.mixpanel.com/track" />
        <meta-data
            android:name="com.mixpanel.android.MPConfig.PeopleEndpoint"
            android:value="https://api-eu.mixpanel.com/engage" />
        <meta-data
            android:name="com.mixpanel.android.MPConfig.GroupsEndpoint"
            android:value="https://api-eu.mixpanel.com/groups" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@mipmap/ic_notif" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorPrimary" />

        <activity
            android:name="com.myzee.witick.features.account.paymentMethods.PaymentMethodsActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.landing.LandingActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.register.RegisterActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize|stateHidden" />
        <activity
            android:name="com.myzee.witick.features.authentication.AuthenticationActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize|stateHidden" />
        <activity
            android:name="com.myzee.witick.features.V3MainActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize|stateHidden" />
        <activity
            android:name="com.myzee.witick.launcher.LauncherActivity"
            android:screenOrientation="portrait"
            android:theme="@style/SplashTheme.LightStatusBar" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.myzee.witick.features.bluetooth.EnableBluetoothActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.payment.scellius.ScelliusActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.location.LocationActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.MainActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.account.information.UserInfoActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.account.information.EditEmailActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize|stateHidden" />
        <activity
            android:name="com.myzee.witick.features.account.information.EditPasswordActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize|stateHidden" />
        <activity
            android:name="com.myzee.witick.features.account.history.HistoryActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.account.history.PurchaseHistoryActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.account.history.ValidationHistoryActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.account.help.HelpActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.account.about.AboutActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.account.help.HelpQuestionActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.common.WebActivity"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.myzee.witick.features.account.code.CodeActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize|stateHidden" />
        <activity
            android:name="com.myzee.witick.features.payment.stripe.StripeActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize|stateHidden" />

        
        <service
            android:name="com.myzee.witick.firebase.MessagingService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        

        <activity
            android:name="com.stripe.android.view.AddPaymentMethodActivity"
            android:theme="@style/StripeDefaultTheme" />
        <activity
            android:name="com.stripe.android.view.PaymentMethodsActivity"
            android:theme="@style/StripeDefaultTheme" />
        <activity
            android:name="com.stripe.android.view.PaymentFlowActivity"
            android:theme="@style/StripeDefaultTheme" />
        <activity
            android:name="com.stripe.android.view.PaymentAuthWebViewActivity"
            android:theme="@style/StripeDefaultTheme"
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name="com.stripe.android.view.PaymentRelayActivity"
            android:theme="@style/StripeDefaultTheme" />
        <activity
            android:name="com.stripe.android.view.Stripe3ds2CompletionActivity"
            android:theme="@style/StripeDefaultTheme" />
        <activity
            android:name="com.stripe.android.paymentsheet.PaymentSheetActivity"
            android:screenOrientation="portrait"
            android:theme="@style/StripePaymentSheetDefaultTheme" />
        <activity
            android:name="com.stripe.android.paymentsheet.PaymentOptionsActivity"
            android:screenOrientation="portrait"
            android:theme="@style/StripePaymentSheetDefaultTheme" />
        <activity
            android:name="com.stripe.android.googlepay.StripeGooglePayActivity"
            android:screenOrientation="portrait"
            android:theme="@style/StripeGooglePayDefaultTheme" />
        <activity
            android:name="com.stripe.android.stripe3ds2.views.ChallengeActivity"
            android:theme="@style/Stripe3DS2Theme" />
        <activity
            android:name="com.stripe.android.stripe3ds2.views.ChallengeProgressActivity"
            android:theme="@style/Stripe3DS2Theme" />
        <activity
            android:name="com.journeyapps.barcodescanner.CaptureActivity"
            android:clearTaskOnLaunch="true"
            android:screenOrientation="sensorLandscape"
            android:stateNotNeeded="true"
            android:theme="@style/zxing_CaptureTheme"
            android:windowSoftInputMode="stateAlwaysHidden" />

        <receiver
            android:name="org.altbeacon.beacon.startup.StartupBroadcastReceiver"
            android:exported="false" >
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.ACTION_POWER_CONNECTED" />
                <action android:name="android.intent.action.ACTION_POWER_DISCONNECTED" />
            </intent-filter>
        </receiver>

        <service
            android:name="org.altbeacon.beacon.service.BeaconService"
            android:enabled="true"
            android:exported="false"
            android:isolatedProcess="false"
            android:label="beacon" />
        <service
            android:name="org.altbeacon.beacon.BeaconIntentProcessor"
            android:enabled="true"
            android:exported="false" />
        <service
            android:name="org.altbeacon.beacon.service.ScanJob"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE" >
            <meta-data
                android:name="immediateScanJobId"
                android:value="208352939" />
            <meta-data
                android:name="periodicScanJobId"
                android:value="208352940" />
        </service>
        <service
            android:name="org.altbeacon.bluetooth.BluetoothTestJob"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE" >
            <meta-data
                android:name="jobId"
                android:value="1799803768" />
        </service>
        <service
            android:name="com.google.firebase.components.ComponentDiscoveryService"
            android:directBootAware="true"
            android:exported="false" >
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.remoteconfig.RemoteConfigRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.crashlytics.CrashlyticsRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.abt.component.AbtRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>

        <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </receiver>
        
        <service
            android:name="com.google.firebase.messaging.FirebaseMessagingService"
            android:directBootAware="true"
            android:exported="false" >
            <intent-filter android:priority="-500" >
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        
        
        
        
        
        
        
        
        
        
        
        <activity android:name="com.mixpanel.android.mpmetrics.MixpanelNotificationRouteActivity" >
        </activity>

        <receiver android:name="com.mixpanel.android.mpmetrics.MixpanelPushNotificationDismissedReceiver" >
        </receiver> 
        <activity
            android:name="com.google.android.play.core.common.PlayCoreDialogWrapperActivity"
            android:exported="false"
            android:stateNotNeeded="true"
            android:theme="@style/Theme.PlayCore.Transparent" /> 
        <uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />

        <activity
            android:name="com.google.android.gms.common.api.GoogleApiActivity"
            android:exported="false"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />

        <provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="com.myzee.witick.debug.firebaseinitprovider"
            android:directBootAware="true"
            android:exported="false"
            android:initOrder="100" />

        <receiver
            android:name="com.google.android.gms.measurement.AppMeasurementReceiver"
            android:enabled="true"
            android:exported="false" >
        </receiver>

        <service
            android:name="com.google.android.gms.measurement.AppMeasurementService"
            android:enabled="true"
            android:exported="false" />
        <service
            android:name="com.google.android.gms.measurement.AppMeasurementJobService"
            android:enabled="true"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE" />

        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <service
            android:name="androidx.room.MultiInstanceInvalidationService"
            android:directBootAware="true"
            android:exported="false" /> 
        <receiver android:name="com.instacart.library.truetime.BootCompletedBroadcastReceiver" >
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.google.android.datatransport.runtime.backends.TransportBackendDiscovery"
            android:exported="false" >
            <meta-data
                android:name="backend:com.google.android.datatransport.cct.CctBackendFactory"
                android:value="cct" />
        </service>

        <provider
            android:name="androidx.lifecycle.ProcessLifecycleOwnerInitializer"
            android:authorities="com.myzee.witick.debug.lifecycle-process"
            android:exported="false"
            android:multiprocess="true" />

        <service
            android:name="com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE" >
        </service>

        <receiver
            android:name="com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver"
            android:exported="false" />
    </application>

</manifest>`

**Comment by FabienWitick** [comment] 2022-06-24 10:43
After checking the library code and debugging process, I figured that `longScanForcingEnabled` is missing from the **BeaconService** metadata.
If I put `<meta-data
                android:name="longScanForcingEnabled"
                android:value="false" />` in the manifest, everything works fine.

**Comment by FabienWitick** [comment] 2022-06-24 13:44
@davidgyoung I think this is the same stack trace. The stack posted by @tonynguyen0523 is the cause of the `RuntimeException` posted by @DarrenMiddleton. I personally have the exact same stack trace on crashlytics.

**Comment by davidgyoung** [comment] 2022-06-24 20:27
Here's a candidate fix:  #1095.   I am putting this into a beta release now, 2.19.5-beta7.  If anyone on this thread with an Android 13 install handy can try that library version and confirm if the crash goes away, I would appreciate it.  The fix looks pretty straightforward.  It will take about an hour for the beta release to show up on Maven central.

**Comment by davidgyoung** [comment] 2022-06-25 16:17
2.19.5-beta7 is now available on Maven Central.

**Comment by FabienWitick** [comment] 2022-06-27 15:03
Just tried 2.19.5-beta7, it seems to work for me. Thank you for this new build @davidgyoung. Do you think we can use this version for production? Or do we stick with this [fix](https://github.com/AltBeacon/android-beacon-library/issues/1083#issuecomment-1165578361)?

**Closed** 2022-06-27 17:34 UTC
