### ISSUE TITLE
Out of Memory Exception with scanJob on Android 8.1.0 

### ISSUE THREAD

**Issue by taucoyote** [AltBeacon/android-beacon-library#647] opened 2018-02-26 16:17 UTC
### Expected behavior

no exception

### Actual behavior

OutOfMemoryError

**log :** 

 D/BluetoothAdapter: isLeEnabled(): ON
02-26 17:05:02.160 16474-21371/com.trustdesigner.trustdesigner D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=5 mScannerId=0
02-26 17:05:03.351 16474-16474/com.trustdesigner.trustdesigner I/ScanJob: Scan job runtime expired: org.altbeacon.beacon.service.ScanJob@b017833
02-26 17:05:03.358 16474-12894/com.trustdesigner.trustdesigner D/BluetoothAdapter: isLeEnabled(): ON
02-26 17:05:03.386 16474-16474/com.trustdesigner.trustdesigner D/BluetoothAdapter: isLeEnabled(): ON
02-26 17:05:12.110 16474-16474/com.trustdesigner.trustdesigner W/JobInfo: Specified interval for 1 is +5m0s0ms. Clamped to +15m0s0ms
02-26 17:05:12.111 16474-16474/com.trustdesigner.trustdesigner W/JobInfo: Specified flex for 1 is 0. Clamped to +5m0s0ms
02-26 17:05:12.111 16474-16474/com.trustdesigner.trustdesigner W/JobInfo: Specified interval for 1 is +5m0s0ms. Clamped to +15m0s0ms
02-26 17:05:12.111 16474-16474/com.trustdesigner.trustdesigner W/JobInfo: Specified flex for 1 is 0. Clamped to +5m0s0ms
02-26 17:05:12.139 16474-16474/com.trustdesigner.trustdesigner I/CycledLeScanner: Using Android O scanner
02-26 17:05:12.161 16474-16474/com.trustdesigner.trustdesigner I/ScanJob: Running immediate scan job: instance is org.altbeacon.beacon.service.ScanJob@7ef8d2d
02-26 17:05:12.200 16474-16474/com.trustdesigner.trustdesigner W/libc: pthread_create failed: couldn't mprotect PROT_NONE 4096-byte stack guard region: Out of memory
02-26 17:05:12.202 16474-16474/com.trustdesigner.trustdesigner W/zygote64: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 17:05:12.222 16474-16474/com.trustdesigner.trustdesigner D/AndroidRuntime: Shutting down VM
02-26 17:05:12.229 16474-16474/com.trustdesigner.trustdesigner E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.trustdesigner.trustdesigner, PID: 16474
                                                                                 java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
                                                                                     at java.lang.Thread.nativeCreate(Native Method)
                                                                                     at java.lang.Thread.start(Thread.java:733)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1377)
                                                                                     at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:651)
                                                                                     at org.altbeacon.beacon.service.ScanHelper.processScanResult(ScanHelper.java:129)
                                                                                     at org.altbeacon.beacon.service.ScanJob.onStartJob(ScanJob.java:66)
                                                                                     at android.app.job.JobService$1.onStartJob(JobService.java:71)
                                                                                     at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-26 17:05:24.074 16474-16485/com.trustdesigner.trustdesigner W/zygote64: Suspending all threads took: 8.354ms
02-26 17:07:52.149 16474-16698/com.trustdesigner.trustdesigner W/libc: pthread_create failed: couldn't mprotect TLS: Out of memory
02-26 17:07:52.163 16474-16698/com.trustdesigner.trustdesigner E/chromium: [ERROR:platform_thread_posix.cc(123)] pthread_create: Try again (11)

### Steps to reproduce this behavior

Just run the application in foreground for quite a time (30min +).

### Mobile device model and OS version

Nexus 6P on 8.1.0

### Android Beacon Library version

2.12.4

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment] 2018-02-28 16:28
Duplicate of #589.  I suspect the issue is that when the ScanJob starts, the whole Application also loads and the onCreate method of the application is called.  If this allocates more memory than Android has available at that time, you'll get a crash as shown.  Please comment on #589 if you have further thoughts about this.

**Closed by davidgyoung** 2018-02-28 16:28 UTC
