### ISSUE TITLE
Android Background Beacon detection not working

### ISSUE THREAD

**Issue by Spectra6170** [AltBeacon/android-beacon-library#1123] opened 2023-01-16 06:53 UTC
When an application is in foreground mode then it is working fine. But when application is closed or in background mode then nothing is working in all version of android mobile devices. And when I manually off Bluetooth and on again then it is working and when screen is locked after that it stopped detecting. Can anyone help me with this? I need background working module for Bluetooth low energy application.

**Comment by davidgyoung** [comment] 2023-01-16 15:15
closed as a duplicate of #1124

**Closed by davidgyoung** 2023-01-16 15:15 UTC
