### ISSUE TITLE
Moto x (2nd generation, Andrioid 5.1): Cannot find any BLE devices after several minutes' scan

### ISSUE THREAD

**Issue by sleepyu** [AltBeacon/android-beacon-library#334] opened 2016-01-25 03:51 UTC
I am simply call startRangingBeaconsInRegion and startMonitoringBeaconsInRegion when beacon service is onBeaconServiceConnect callback. 
In the beginning, AltBeacon works well, finding BLE devices all the time. however, after running for about 30min (or even longer, 2 hours maybe), the application cannot find any BLE devices. I also tried the system Bluetooth search (in phone's config->Bluetooth, click ), also no devices including BLE devices and Bluetooth 3 devices can be found. 
Attached please find the logcat file before and after the issue happens. this issue also repro on Xiaomi （Chinese brand ranked 4th in the world I think）, however, this issue doesn't repro on Samsung, Nubia, Huawei and Meizu. 
	@Override
	public void onBeaconServiceConnect() {

		mBeaconManger.setRangeNotifier(this);
		// for test
		// mBeaconManger.setMonitorNotifier(this);

		Log.i(TAG, "beaconManager.startRangingBeaconsInRegion(REGION)");
		// tell the beaconService to start looking for beacons the mathch the
		// passes Region Object.
		// and providing updates on the estimated mDistance every seconds while
		// beacons in the Region are visible
		try {
			mBeaconManger.startRangingBeaconsInRegion(new Region(
					"com.virgil.test", Identifier.fromUuid(TEST_UUID), null,
					null));
		} catch (RemoteException e) {
			e.printStackTrace();
		}

		// tell the beaconService to start looking for beacons the mathch the
		// passes Region Object.
		try {
			mBeaconManger.startMonitoringBeaconsInRegion(new Region(
					"com.virgil.test", Identifier.fromUuid(TEST_UUID), null,
					null));
		} catch (RemoteException e) {
			e.printStackTrace();
		}

	}
[moto_beacon_logcat.txt](https://github.com/AltBeacon/android-beacon-library/files/102744/moto_beacon_logcat.txt)

**Comment by davidgyoung** [comment] 2016-01-25 16:26
@sleepyu, thanks for this report.  This is a known issue with some firmware versions, which is not specific to this library.  It happens on long periods of bluetooth scanning.  Closing this  issue as it is a duplicate of #289

**Closed by davidgyoung** 2016-01-25 16:26 UTC
